---
services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      PORKBUN_SECRET_API_KEY: ${PORKBUN_SECRET_API_KEY}
      PORKBUN_API_KEY: ${PORKBUN_API_KEY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/acme.json:/acme.json
      - ./traefik/config.yml:/config.yml:ro
    labels:
      - "traefik.enable=true"

      # HTTP Rules
      - "traefik.http.routers.traefik.entrypoints=http"
      # - "traefik.http.routers.traefik.rule=Host(`traefik.justinmountain.com`)"
      
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      
      # HTTPs Rules
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      # - "traefik.http.routers.traefik-secure.rule=Host(`traefik.justinmountain.com`)"


      # Certificate resolution
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=porkbun"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=justinmountain.com"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.justinmountain.com"

      # Dashboard access
      # - "traefik.http.routers.traefik-secure.service=api@internal"

    restart: unless-stopped

networks:
  proxy:
    external: true
