---
- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Reset SSH connection to allow user changes to affect 'current login user'
  meta: reset_connection
